### ISSUE TITLE
Token in config.ini

### ISSUE THREAD

**Issue by Mattia7494789** [dz-paji/Pterodactyl-TG-Bot#1]
I put the token in the config.ini file taken from @botfather:

ACCESS_TOKEN = 'my_token'

when i start the server it says: invalid token

**Comment by dz-paji** [comment]
Maybe it's due to an update of Bot API from telegram, as this project is untouched for 2 years. I will have a look around this.

**Comment by dz-paji** [comment]
It's really just bad documentation. In config.ini, remove the `'` surrounding your bot token. That should solve the problem.
